name: FileHold Systems Inc.
favicon: null
layout_spectrum: 0.2726360058877617
typography_spectrum: 0.0017288238741457462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5831209279131144
  lightness: 0.25400139880366623
  saturation: 0.4644438340328634
  rhythmicContrast: 0.6324245329014957
purpose: []
