name: FileHold Systems Inc.
favicon: null
layout_spectrum: 0.51348
typography_spectrum: 0.5629
title: FileHold Document and Record Lifecycle Software
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#026993'
    - '#75c260'
    - '#bbdfaf'
    - '#2f2d2e'
  brandStrength: 0.8125
  lightness: 0.25400139880366623
  saturation: 0.4644438340328634
  rhythmicContrast: 0.6324245329014957
purpose: []
